apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sample-dotnet-app
  name: sample-dotnet-app-config
  namespace: "$APP_NAMESPACE"
type: Opaque
stringData:
  appusers.json: |-
    {
      "AppUsers" : [{
        "Id": "user",
        "Password": "usrpass",
        "FirstName": "Application",
        "LastName": "User"
      },{
        "Id": "admin",
        "Password": "admpass",
        "FirstName": "System",
        "LastName": "Administrator"
      }]
    }