apiVersion: v1
kind: Pod
spec:
    serviceAccountName: jenkins-privileged
    containers:
      - name: buildah
        image: saharshsingh/container-management:1.0-30 # need to change
        imagePullPolicy: IfNotPresent
        command:
          - /bin/cat
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /var/lib/containers
            name: buildah-storage
    volumes:
      - name: buildah-storage
        emptyDir: {}