apiVersion: v1
kind: Pod
spec:
    containers:
      - name: jnlp
        image: 'jenkinsci/jnlp-slave:alpine'
        env:
          JENKINS_URL: jenkins.operations:8080
          JENKINS_TUNNEL: jenkins-agent.operations:50002
      - name: dotnet
        image: mcr.microsoft.com/dotnet/sdk:6.0
        imagePullPolicy: IfNotPresent
        command:
          - /bin/cat
        tty: true