apiVersion: v1
kind: Pod
spec:
    containers:
      - name: dotnet
        image: mcr.microsoft.com/dotnet/sdk:6.0.302-alpine3.16-amd64
        imagePullPolicy: IfNotPresent
        command:
          - /bin/cat
        tty: true